# Generated by Django 5.2.1 on 2025-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='show_students_publicly',
            field=models.BooleanField(default=True, help_text='Display student list publicly for this class.'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'ছাত্র'), ('Female', 'ছাত্রী'), ('Other', 'অন্যান্য')], default='Male', max_length=10, verbose_name='লিঙ্গ'),
        ),
    ]
