# Generated by Django 5.2.1 on 2025-08-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_class_show_students_publicly_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='female_student',
            field=models.IntegerField(default=0, verbose_name='Female Students'),
        ),
        migrations.AddField(
            model_name='class',
            name='male_student',
            field=models.IntegerField(default=0, verbose_name='Male Students'),
        ),
    ]
