# Generated by Django 5.2.1 on 2025-08-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_class_female_student_class_male_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='female_student',
        ),
        migrations.RemoveField(
            model_name='class',
            name='male_student',
        ),
    ]
