# Generated by Django 5.2.1 on 2025-08-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_class_female_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='female_student',
            field=models.IntegerField(default=0, verbose_name='Female Students (Manual)'),
        ),
        migrations.AddField(
            model_name='class',
            name='male_student',
            field=models.IntegerField(default=0, verbose_name='Male Students (Manual)'),
        ),
    ]
