# Generated by Django 5.2.1 on 2025-08-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_class_female_student_class_male_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmessage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='about/message/', verbose_name='ছবি'),
        ),
        migrations.AlterField(
            model_name='aboutmessage',
            name='show_on_home_page',
            field=models.BooleanField(help_text='হোম পেজে দেখানোর জন্য টিক দিন। শুধুমাত্র serial_no=1 এর জন্য সক্রিয় করুন।', verbose_name='হোম পেজে দেখান'),
        ),
    ]
