# Generated by Django 5.2.1 on 2025-08-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_aboutmessage_show_on_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmessage',
            name='show_on_home_page',
            field=models.BooleanField(default=False, help_text='হোম পেজে দেখানোর জন্য টিক দিন। শুধুমাত্র একটি বার্তা সিলেক্ট করা যাবে।', verbose_name='হোম পেজে দেখান'),
        ),
    ]
