# Generated by Django 5.2.1 on 2025-08-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_aboutmessage_show_on_home_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
