# Generated by Django 5.2.1 on 2025-08-12 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_delete_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('notice', 'Notice'), ('result', 'Result'), ('admission', 'Admission'), ('routine', 'Routine')], max_length=20)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='notices/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
