# Generated by Django 5.2.1 on 2025-08-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrincipalMessage',
        ),
    ]
