# Generated by Django 5.2.1 on 2025-08-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_delete_principalmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutLink',
        ),
        migrations.DeleteModel(
            name='InformationSlider',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-updated_at'], 'verbose_name': 'বই', 'verbose_name_plural': 'বইসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'ক্লাসের তথ্য'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'বিভাগের তথ্য'},
        ),
        migrations.AlterModelOptions(
            name='facultymember',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Faculty Member', 'verbose_name_plural': 'কর্মকর্তাদের তথ্য'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'গ্যালারী'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': 'নোটিশ'},
        ),
        migrations.AlterModelOptions(
            name='principalrole',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'গুরুত্বপূর্ণ পদ', 'verbose_name_plural': 'গুরুত্বপূর্ণ পদ সমূহ'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-created_at'], 'verbose_name': 'ফলাফল', 'verbose_name_plural': 'ফলাফলসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['-updated_at'], 'verbose_name': 'রুটিন', 'verbose_name_plural': 'রুটিন সমূহ'},
        ),
        migrations.AlterModelOptions(
            name='routinetype',
            options={'verbose_name': 'রুটিনের ধারা', 'verbose_name_plural': 'রুটিনের ধারা সমূহ'},
        ),
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name_plural': 'স্কুলের তথ্য'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'স্লাইডার'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'শিক্ষার্থীদের তথ্য'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['-updated_at'], 'verbose_name': 'পাঠ্যক্রম', 'verbose_name_plural': 'পাঠ্যক্রম সমূহ'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'শিক্ষকদের তথ্য'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'ভিডিও'},
        ),
        migrations.AddField(
            model_name='department',
            name='female_student',
            field=models.IntegerField(default=0, verbose_name='Female Students (Manual)'),
        ),
        migrations.AddField(
            model_name='department',
            name='male_student',
            field=models.IntegerField(default=0, verbose_name='Male Students (Manual)'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='School Description'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='School History'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='School Mission'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='School Vision'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
