# Generated by Django 5.2.1 on 2025-08-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_delete_aboutlink_delete_informationslider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationService',
        ),
        migrations.AlterModelOptions(
            name='facilityinfo',
            options={'ordering': ['order', '-created_at'], 'verbose_name_plural': 'সুযোগ সুবিধার তথ্য'},
        ),
        migrations.AlterModelOptions(
            name='facilitytype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'সুযোগ সুবিধা', 'verbose_name_plural': 'সুযোগ সুবিধাসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='facultyinfo',
            options={'ordering': ['order', '-created_at'], 'verbose_name_plural': 'কমিটির তথ্য'},
        ),
    ]
