# Generated by Django 5.2.1 on 2025-08-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'নোটিশসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='noticetype',
            options={'verbose_name_plural': 'নোটিশের ধরন'},
        ),
    ]
